### ISSUE TITLE
Profiler ToDo

### ISSUE THREAD

**Issue by domoritz** [uwescience/myria-web#226]
- [ ] Animate sort in network view like [here](http://bost.ocks.org/mike/miserables/)
- [x] Collapse in the fragment overview if fragment is collapsed in graph
- [x] Allow expanding without activating
- [x] Show time for communication rather than query runtime in network view

**Comment by domoritz** [comment]
@BrandonHaynes @shrjain feel free to add issues if you run into them as you work on the profiler.
